I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 167, in script
    init python:
  File "game/script.rpy", line 170, in <module>
    json.dump(Character1.encode('utf8'), file, indent = 4)
AttributeError: 'RevertableDict' object has no attribute 'encode'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 167, in script
    init python:
  File "C:\Users\xizzi\OneDrive\Рабочий стол\xizzin\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\xizzi\OneDrive\Рабочий стол\xizzin\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 170, in <module>
    json.dump(Character1.encode('utf8'), file, indent = 4)
AttributeError: 'RevertableDict' object has no attribute 'encode'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
study 1.0
Fri Nov 10 09:21:10 2023
